//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foreworld.Cmd.Build {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foreworld.Cmd.Build.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 数据源服务执行失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DataSourceCmd_Err_1 {
            get {
                return ResourceManager.GetString("DataSourceCmd_Err_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取数据源记录失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DataSourceCmd_Err_2 {
            get {
                return ResourceManager.GetString("DataSourceCmd_Err_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select dstype,sqls from p_datasource where id=@id 的本地化字符串。
        /// </summary>
        internal static string DataSourceCmd_Sql {
            get {
                return ResourceManager.GetString("DataSourceCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select t.* from ( 的本地化字符串。
        /// </summary>
        internal static string DataSourceCmd_Sql_1 {
            get {
                return ResourceManager.GetString("DataSourceCmd_Sql_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似      @where) t where t.rowNum between (@current-1)*@pagesize+1 and @current*@pagesize 的本地化字符串。
        /// </summary>
        internal static string DataSourceCmd_Sql_2 {
            get {
                return ResourceManager.GetString("DataSourceCmd_Sql_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   @current, @pagesize, @where 的本地化字符串。
        /// </summary>
        internal static string DataSourceCmd_Sql_3 {
            get {
                return ResourceManager.GetString("DataSourceCmd_Sql_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取数据源列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListDataSourcesCmd_Err {
            get {
                return ResourceManager.GetString("ListDataSourcesCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.id,a.dsdesc,d.codename dstype_text,a.sqls,a.testparams,a.addtime
        ///,c.username ad_s_user_name,b.codename isenable_text 
        ///from 
        ///p_datasource a, p_code b,s_user c,p_code d
        ///where 
        ///a.dstype=d.code and d.tab_p_codetype_id=&apos;DSTYPE&apos; and
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id order by a.dstype,a.addtime asc 的本地化字符串。
        /// </summary>
        internal static string ListDataSourcesCmd_Sql {
            get {
                return ResourceManager.GetString("ListDataSourcesCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取页面代码生成树列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListPageCodeTreeCmd_Err {
            get {
                return ResourceManager.GetString("ListPageCodeTreeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select tt.* from (SELECT &apos;d&apos;+CAST(a.id AS varchar) id,&apos;0&apos; p_id,a.tab_p_ds_id nodename,&apos;d&apos; v0,a.params v1,&apos;&apos; v2,&apos;&apos; v3 from s_page_ds a WHERE a.tab_s_page_id=@pageid
        ///union all
        ///SELECT &apos;w&apos;+CAST(t1.id AS varchar) id,&apos;d&apos;+CAST(t1.tab_s_page_ds_id AS varchar) p_id,t2.widget_name+&apos;_&apos;+CAST(t1.id AS varchar) nodename,
        ///&apos;w&apos; v0,
        ///t2.widget_name v1,
        ///t2.classpath v2,t2.ver v3 from (
        ///SELECT a.* FROM s_page_ds_wg a WHERE a.tab_s_page_ds_id IN (select id from s_page_ds where tab_s_page_id=@pageid)) t1,
        ///s_widget t2
        ///WHER [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ListPageCodeTreeCmd_Sql {
            get {
                return ResourceManager.GetString("ListPageCodeTreeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取页数据源列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListPageDssCmd_Err {
            get {
                return ResourceManager.GetString("ListPageDssCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select e.id,a.dsdesc,d.codename dstype_text,a.sqls,a.testparams,e.params,a.addtime
        ///,c.username ad_s_user_name,b.codename isenable_text 
        ///from 
        ///p_datasource a, p_code b,s_user c,p_code d,s_page_ds e
        ///where 
        ///a.dstype=d.code and d.tab_p_codetype_id=&apos;DSTYPE&apos; and
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and
        ///a.id=e.tab_p_ds_id and e.tab_s_page_id=@pageid
        ///order by a.dstype,a.addtime asc 的本地化字符串。
        /// </summary>
        internal static string ListPageDssCmd_Sql {
            get {
                return ResourceManager.GetString("ListPageDssCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取页数据源组件参数列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListPageDsWdParamsCmd_Err {
            get {
                return ResourceManager.GetString("ListPageDsWdParamsCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select id,param_name,param_desc,relatparam from (select a.*,b.id tab_s_page_ds_wg_id from s_widget_param a, s_page_ds_wg b
        ///
        ///where
        ///b.tab_s_widget_id=a.tab_s_widget_id and
        ///b.id=@pagedswgid) t1 left join s_page_ds_wg_param t2
        ///on
        ///t1.id=t2.tab_s_widget_param_id and t1.tab_s_page_ds_wg_id=t2.tab_s_page_ds_wg_id 的本地化字符串。
        /// </summary>
        internal static string ListPageDsWdParamsCmd_Sql {
            get {
                return ResourceManager.GetString("ListPageDsWdParamsCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取页数据源组件列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListPageDsWdsCmd_Err {
            get {
                return ResourceManager.GetString("ListPageDsWdsCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 
        ///a.id,b.widget_name,b.classpath,b.ver,c.codename widgetype_text,b.widget_desc,a.funcdesc,b.addtime
        ///,e.username ad_s_user_name
        ///,d.codename isenable_text,b.id widget_id  from 
        ///
        ///s_page_ds_wg a,s_widget b,p_code c,p_code d,s_user e
        ///
        ///where 
        ///b.isenable=d.code and d.tab_p_codetype_id=&apos;ISENABLE&apos; and
        ///b.tab_p_code_widgetype_id=c.code and c.tab_p_codetype_id=&apos;WIDGETYPE&apos; and
        ///a.tab_s_widget_id=b.id and b.ad_s_user_id=e.id and
        ///a.tab_s_page_ds_id=@pagedsid 的本地化字符串。
        /// </summary>
        internal static string ListPageDsWdsCmd_Sql {
            get {
                return ResourceManager.GetString("ListPageDsWdsCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取页面树列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListPageTreeCmd_Err {
            get {
                return ResourceManager.GetString("ListPageTreeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.code id,a.p_code p_id,a.codename nodename,1 nodetype,&apos;&apos; v0,&apos;&apos; v1,a.addtime,a.ad_s_user_id,a.editime,a.ed_s_user_id,a.isenable,a.invalid from p_code a where a.tab_p_codetype_id=&apos;PAGEFOLDER&apos; collate Chinese_PRC_CS_AI
        ///union ALL
        ///select &apos;p&apos;+CAST(b.id AS varchar) id,b.tab_p_code_pagefolder_id p_id,b.page_name+&apos;(&apos;+ b.page_desc +&apos;)&apos; nodename,2 nodetype,b.page_name v0,b.page_desc v1,b.addtime,b.ad_s_user_id,b.editime,b.ed_s_user_id,b.isenable,b.invalid from s_page b 的本地化字符串。
        /// </summary>
        internal static string ListPageTreeCmd_Sql {
            get {
                return ResourceManager.GetString("ListPageTreeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取表树列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListTableTreeCmd_Err {
            get {
                return ResourceManager.GetString("ListTableTreeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT a.id,0 p_id,a.alias FROM s_table a order by a.id 的本地化字符串。
        /// </summary>
        internal static string ListTableTreeCmd_Sql {
            get {
                return ResourceManager.GetString("ListTableTreeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取组件参数列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListWidgetParamsCmd_Err {
            get {
                return ResourceManager.GetString("ListWidgetParamsCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select param_name+&apos;|&apos;+CAST(tab_s_widget_id AS varchar) id,param_name,param_desc,a.addtime
        ///,c.username ad_s_user_name,b.codename isenable_text from s_widget_param a, p_code b,s_user c 
        ///where 
        ///a.tab_s_widget_id=@widgetid and
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id 的本地化字符串。
        /// </summary>
        internal static string ListWidgetParamsCmd_Sql {
            get {
                return ResourceManager.GetString("ListWidgetParamsCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取组件树列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListWidgeTreeCmd_Err {
            get {
                return ResourceManager.GetString("ListWidgeTreeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.code id,a.p_code p_id,a.codename nodename,1 nodetype,&apos;&apos; ttip,a.addtime,a.ad_s_user_id,a.editime,a.ed_s_user_id,a.isenable,a.invalid from p_code a where a.tab_p_codetype_id=&apos;WIDGETYPE&apos; collate Chinese_PRC_CS_AI
        ///union ALL
        ///select &apos;w&apos;+CAST(b.id AS varchar) id,b.tab_p_code_widgetype_id p_id,b.widget_name+&apos;_v&apos;+b.ver+&apos;(&apos;+ b.widget_desc +&apos;)&apos; nodename,2 nodetype,b.classpath ttip,b.addtime,b.ad_s_user_id,b.editime,b.ed_s_user_id,b.isenable,b.invalid from s_widget b 的本地化字符串。
        /// </summary>
        internal static string ListWidgeTreeCmd_Sql {
            get {
                return ResourceManager.GetString("ListWidgeTreeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源服务执行失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string SDSCmd_Err_1 {
            get {
                return ResourceManager.GetString("SDSCmd_Err_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取数据源记录失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string SDSCmd_Err_2 {
            get {
                return ResourceManager.GetString("SDSCmd_Err_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select dstype,sqls from p_datasource where safetype=1 and id=@id 的本地化字符串。
        /// </summary>
        internal static string SDSCmd_Sql {
            get {
                return ResourceManager.GetString("SDSCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select t.* from ( 的本地化字符串。
        /// </summary>
        internal static string SDSCmd_Sql_1 {
            get {
                return ResourceManager.GetString("SDSCmd_Sql_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @where) t where t.rowNum between (@current-1)*@pagesize+1 and @current*@pagesize 的本地化字符串。
        /// </summary>
        internal static string SDSCmd_Sql_2 {
            get {
                return ResourceManager.GetString("SDSCmd_Sql_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @current, @pagesize, @where 的本地化字符串。
        /// </summary>
        internal static string SDSCmd_Sql_3 {
            get {
                return ResourceManager.GetString("SDSCmd_Sql_3", resourceCulture);
            }
        }
    }
}
