//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foreworld.Cmd.Sysmanage {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foreworld.Cmd.Sysmanage.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加新代码[{0}] 的本地化字符串。
        /// </summary>
        internal static string AddCodeCmd {
            get {
                return ResourceManager.GetString("AddCodeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新代码添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddCodeCmd_Err {
            get {
                return ResourceManager.GetString("AddCodeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3013 的本地化字符串。
        /// </summary>
        internal static string AddCodeCmd_Err_Code {
            get {
                return ResourceManager.GetString("AddCodeCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into p_code (code,tab_p_codetype_id,p_code,codename,codedesc,sort,addtime,ad_s_user_id,isenable,invalid) values (@code, @tab_p_codetype_id, @p_code,@codename, @codedesc, @sort, @addtime, @ad_s_user_id, @isenable, @invalid);
        ///select a.code+&apos;,&apos;+a.tab_p_codetype_id id,a.*,b.codename isenable_text,c.username ad_s_user_name from p_code a, p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.tab_p_codetype_id=@tab_p_codetype_id and a.code=@code; 的本地化字符串。
        /// </summary>
        internal static string AddCodeCmd_Sql {
            get {
                return ResourceManager.GetString("AddCodeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新代码类型[{0}] 的本地化字符串。
        /// </summary>
        internal static string AddCodeTypeCmd {
            get {
                return ResourceManager.GetString("AddCodeTypeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新代码类型添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddCodeTypeCmd_Err {
            get {
                return ResourceManager.GetString("AddCodeTypeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3009 的本地化字符串。
        /// </summary>
        internal static string AddCodeTypeCmd_Err_Code {
            get {
                return ResourceManager.GetString("AddCodeTypeCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into p_codetype (id,codetypedesc,addtime,ad_s_user_id,isenable,invalid) values (@id, @codetypedesc, @addtime, @ad_s_user_id, @isenable, @invalid);
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from p_codetype a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string AddCodeTypeCmd_Sql {
            get {
                return ResourceManager.GetString("AddCodeTypeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新模块[{0}] 的本地化字符串。
        /// </summary>
        internal static string AddModuleCmd {
            get {
                return ResourceManager.GetString("AddModuleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新模块添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddModuleCmd_Err {
            get {
                return ResourceManager.GetString("AddModuleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3005 的本地化字符串。
        /// </summary>
        internal static string AddModuleCmd_Err_Code {
            get {
                return ResourceManager.GetString("AddModuleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into s_module (p_id,modulename,href,sort,icon,addtime,ad_s_user_id,isenable,invalid) values (@p_id, @modulename, @href, @sort, @icon, @addtime, @ad_s_user_id, @isenable, @invalid);
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from s_module a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=SCOPE_IDENTITY(); 的本地化字符串。
        /// </summary>
        internal static string AddModuleCmd_Sql {
            get {
                return ResourceManager.GetString("AddModuleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新网址添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddMyUrlCmd_Err {
            get {
                return ResourceManager.GetString("AddMyUrlCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into p_myurl (url,memo,tab_p_code_ispublic_id,addtime,opt_s_user_id,isenable,invalid) values (@url,@memo,@tab_p_code_ispublic_id, @addtime, @opt_s_user_id, @isenable, @invalid);
        ///select 
        ///a.*,b.codename isenable_text,c.username opt_s_user_name,d.codename ispublic_text 
        ///from 
        ///p_myurl a,p_code b,s_user c,p_code d
        ///where 
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; 
        ///and a.tab_p_code_ispublic_id=d.code and d.tab_p_codetype_id=&apos;ISPUBLIC&apos; 
        ///and a.opt_s_user_id=c.id 
        ///and a.id=SCOPE_IDENTITY(); 的本地化字符串。
        /// </summary>
        internal static string AddMyUrlCmd_Sql {
            get {
                return ResourceManager.GetString("AddMyUrlCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新组织添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddOrgCmd_Err {
            get {
                return ResourceManager.GetString("AddOrgCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into s_org (p_id,orgname,orgdesc,tab_s_orgtype_id,sort,addtime,opt_s_user_id,isenable,invalid) values (@p_id, @orgname, @orgdesc, @tab_s_orgtype_id, @sort, @addtime, @opt_s_user_id, @isenable, @invalid);
        ///select a.*,b.codename isenable_text,c.username opt_s_user_name from s_org a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.opt_s_user_id=c.id and a.id=SCOPE_IDENTITY(); 的本地化字符串。
        /// </summary>
        internal static string AddOrgCmd_Sql {
            get {
                return ResourceManager.GetString("AddOrgCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新角色[{0}] 的本地化字符串。
        /// </summary>
        internal static string AddRoleCmd {
            get {
                return ResourceManager.GetString("AddRoleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新角色添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddRoleCmd_Err {
            get {
                return ResourceManager.GetString("AddRoleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3017 的本地化字符串。
        /// </summary>
        internal static string AddRoleCmd_Err_Code {
            get {
                return ResourceManager.GetString("AddRoleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into s_role (tab_s_rolegroup_id,rolename,roledesc,startime,endtime,addtime,ad_s_user_id,isenable,invalid) values (@tab_s_rolegroup_id,@rolename, @roledesc, DATEADD(s,@startime,&apos;1970-01-01 00:00:00&apos;), DATEADD(s,@endtime,&apos;1970-01-01 00:00:00&apos;), @addtime, @ad_s_user_id, @isenable, @invalid);
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from s_role a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=SCOPE_IDENTITY(); 的本地化字符串。
        /// </summary>
        internal static string AddRoleCmd_Sql {
            get {
                return ResourceManager.GetString("AddRoleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新角色组[{0}] 的本地化字符串。
        /// </summary>
        internal static string AddRoleGroupCmd {
            get {
                return ResourceManager.GetString("AddRoleGroupCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新角色组添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddRoleGroupCmd_Err {
            get {
                return ResourceManager.GetString("AddRoleGroupCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3028 的本地化字符串。
        /// </summary>
        internal static string AddRoleGroupCmd_Err_Code {
            get {
                return ResourceManager.GetString("AddRoleGroupCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into s_rolegroup (id,rolegroupdesc,addtime,ad_s_user_id,isenable,invalid) values (@id, @rolegroupdesc, @addtime, @ad_s_user_id, @isenable, @invalid);
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from s_rolegroup a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string AddRoleGroupCmd_Sql {
            get {
                return ResourceManager.GetString("AddRoleGroupCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新用户添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddUserCmd_Err {
            get {
                return ResourceManager.GetString("AddUserCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3001 的本地化字符串。
        /// </summary>
        internal static string AddUserCmd_Err_Code {
            get {
                return ResourceManager.GetString("AddUserCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into s_user 
        ///(username,password,sex,alias,firstname,lastname,qq,email,idcard,mobile,fax,addtime,opt_s_user_id,isenable,invalid) 
        ///values 
        ///(@username,@password,@sex,@alias,@firstname,@lastname,@qq,@email,@idcard,@mobile,@fax,@addtime,@opt_s_user_id,@isenable,@invalid)
        ///select 
        ///a.id,a.username,a.sex,a.alias,a.firstname,a.lastname,
        ///a.firstname+a.lastname as realname,a.qq,a.email,a.idcard,a.mobile,a.fax,a.last_logoutime,
        ///a.addtime,a.opt_s_user_id,a.isenable,a.invalid,b.codename isenable_text 
        ///from  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AddUserCmd_Sql {
            get {
                return ResourceManager.GetString("AddUserCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除代码[{0}] 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeCmd {
            get {
                return ResourceManager.GetString("DeleteCodeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码删除失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeCmd_Err {
            get {
                return ResourceManager.GetString("DeleteCodeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3015 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeCmd_Err_Code {
            get {
                return ResourceManager.GetString("DeleteCodeCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from p_code where tab_p_codetype_id=@tab_p_codetype_id and code=@code; 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteCodeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除代码类型[{0}] 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeTypeCmd {
            get {
                return ResourceManager.GetString("DeleteCodeTypeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码类型删除失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeTypeCmd_Err {
            get {
                return ResourceManager.GetString("DeleteCodeTypeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3011 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeTypeCmd_Err_Code {
            get {
                return ResourceManager.GetString("DeleteCodeTypeCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from p_codetype where id=@id 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeTypeCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteCodeTypeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from p_code where tab_p_codetype_id = @id 的本地化字符串。
        /// </summary>
        internal static string DeleteCodeTypeCmd_Sql2 {
            get {
                return ResourceManager.GetString("DeleteCodeTypeCmd_Sql2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除模块[{0}] 的本地化字符串。
        /// </summary>
        internal static string DeleteModuleCmd {
            get {
                return ResourceManager.GetString("DeleteModuleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块删除失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DeleteModuleCmd_Err {
            get {
                return ResourceManager.GetString("DeleteModuleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3008 的本地化字符串。
        /// </summary>
        internal static string DeleteModuleCmd_Err_Code {
            get {
                return ResourceManager.GetString("DeleteModuleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from s_module where id in (0@ids); 的本地化字符串。
        /// </summary>
        internal static string DeleteModuleCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteModuleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from p_myurl where opt_s_user_id=@opt_s_user_id and id in (0@ids); 的本地化字符串。
        /// </summary>
        internal static string DeleteMyUrlCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteMyUrlCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from s_org where id in (0@ids); 的本地化字符串。
        /// </summary>
        internal static string DeleteOrgCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteOrgCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除角色[{0}] 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleCmd {
            get {
                return ResourceManager.GetString("DeleteRoleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色删除失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleCmd_Err {
            get {
                return ResourceManager.GetString("DeleteRoleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3019 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleCmd_Err_Code {
            get {
                return ResourceManager.GetString("DeleteRoleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from s_role where id in (0@ids); 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteRoleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除角色组[{0}] 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleGroupCmd {
            get {
                return ResourceManager.GetString("DeleteRoleGroupCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色组删除失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleGroupCmd_Err {
            get {
                return ResourceManager.GetString("DeleteRoleGroupCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3030 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleGroupCmd_Err_Code {
            get {
                return ResourceManager.GetString("DeleteRoleGroupCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from s_rolegroup where id=@id 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleGroupCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteRoleGroupCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from s_role where tab_s_rolegroup_id=@id 的本地化字符串。
        /// </summary>
        internal static string DeleteRoleGroupCmd_Sql2 {
            get {
                return ResourceManager.GetString("DeleteRoleGroupCmd_Sql2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from s_user where id in (0@ids); 的本地化字符串。
        /// </summary>
        internal static string DeleteUserCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteUserCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取用户照片失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string DownloadMyPhotoCmd_Err {
            get {
                return ResourceManager.GetString("DownloadMyPhotoCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3026 的本地化字符串。
        /// </summary>
        internal static string DownloadMyPhotoCmd_Err_Code {
            get {
                return ResourceManager.GetString("DownloadMyPhotoCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from s_user where photo is not null and id=@id 的本地化字符串。
        /// </summary>
        internal static string DownloadMyPhotoCmd_Sql {
            get {
                return ResourceManager.GetString("DownloadMyPhotoCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色授权失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string EmpowerRoleCmd_Err {
            get {
                return ResourceManager.GetString("EmpowerRoleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3032 的本地化字符串。
        /// </summary>
        internal static string EmpowerRoleCmd_Err_Code {
            get {
                return ResourceManager.GetString("EmpowerRoleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into s_role_modopt (tab_s_modopt_id,tab_s_role_id,addtime,ad_s_user_id,isenable,invalid) values (@tab_s_modopt_id, @tab_s_role_id, @addtime, @ad_s_user_id, @isenable, @invalid);
        ///select a.*,b.codename isenable_text,c.username opt_s_user_name from s_role_modopt a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.tab_s_modopt_id=@tab_s_modopt_id and a.tab_s_role_id=@tab_s_role_id; 的本地化字符串。
        /// </summary>
        internal static string EmpowerRoleCmd_Sql {
            get {
                return ResourceManager.GetString("EmpowerRoleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListCodesCmd_Err {
            get {
                return ResourceManager.GetString("ListCodesCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3016 的本地化字符串。
        /// </summary>
        internal static string ListCodesCmd_Err_Code {
            get {
                return ResourceManager.GetString("ListCodesCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.code+&apos;,&apos;+a.tab_p_codetype_id id,a.*,b.codename isenable_text,c.username ad_s_user_name from p_code a, p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.tab_p_codetype_id=@tab_p_codetype_id order by a.sort asc 的本地化字符串。
        /// </summary>
        internal static string ListCodesCmd_Sql {
            get {
                return ResourceManager.GetString("ListCodesCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码类型列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListCodeTypesCmd_Err {
            get {
                return ResourceManager.GetString("ListCodeTypesCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3012 的本地化字符串。
        /// </summary>
        internal static string ListCodeTypesCmd_Err_Code {
            get {
                return ResourceManager.GetString("ListCodeTypesCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.*,b.codename isenable_text,c.username ad_s_user_name from p_codetype a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id order by a.id asc 的本地化字符串。
        /// </summary>
        internal static string ListCodeTypesCmd_Sql {
            get {
                return ResourceManager.GetString("ListCodeTypesCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源列表失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListDataSourcesCmd_Err {
            get {
                return ResourceManager.GetString("ListDataSourcesCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3034 的本地化字符串。
        /// </summary>
        internal static string ListDataSourcesCmd_Err_Code {
            get {
                return ResourceManager.GetString("ListDataSourcesCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.id,a.dsname,d.codename dstype_text,a.dsdesc,a.sqls,a.addtime
        ///,c.username ad_s_user_name,b.codename isenable_text 
        ///from 
        ///p_datasource a, p_code b,s_user c,p_code d
        ///where 
        ///a.dstype=d.code and d.tab_p_codetype_id=&apos;DSTYPE&apos; and
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id order by a.id asc 的本地化字符串。
        /// </summary>
        internal static string ListDataSourcesCmd_Sql {
            get {
                return ResourceManager.GetString("ListDataSourcesCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块操作列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListModOptsCmd_Err {
            get {
                return ResourceManager.GetString("ListModOptsCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.*,b.codename isenable_text,c.username opt_s_user_name from s_modopt a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.opt_s_user_id=c.id and a.tab_s_module_id=@tab_s_module_id order by a.tab_p_code_moptype_id asc 的本地化字符串。
        /// </summary>
        internal static string ListModOptsCmd_Sql {
            get {
                return ResourceManager.GetString("ListModOptsCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListModulesCmd_Err {
            get {
                return ResourceManager.GetString("ListModulesCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3007 的本地化字符串。
        /// </summary>
        internal static string ListModulesCmd_Err_Code {
            get {
                return ResourceManager.GetString("ListModulesCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.id, a.modulename, a.href,a.moduledesc, a.icon, a.sort, a.addtime,c.username ad_s_user_name, b.codename isenable_text,a.p_id 
        ///from s_module a,p_code b,s_user c 
        ///where 
        ///a.modtype=1 and a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id
        ///@appendSQL
        ///order by a.p_id,a.sort,a.id asc 的本地化字符串。
        /// </summary>
        internal static string ListModulesCmd_Sql {
            get {
                return ResourceManager.GetString("ListModulesCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListMyUrlsCmd_Err {
            get {
                return ResourceManager.GetString("ListMyUrlsCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 
        ///a.*,b.codename isenable_text,c.username opt_s_user_name,d.codename ispublic_text 
        ///from 
        ///p_myurl a,p_code b,s_user c,p_code d
        ///where 
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; 
        ///and a.tab_p_code_ispublic_id=d.code and d.tab_p_codetype_id=&apos;ISPUBLIC&apos; 
        ///and a.opt_s_user_id=c.id 
        ///and (a.tab_p_code_ispublic_id=1 or a.opt_s_user_id=@opt_s_user_id) 
        ///order by a.id desc 的本地化字符串。
        /// </summary>
        internal static string ListMyUrlsCmd_Sql {
            get {
                return ResourceManager.GetString("ListMyUrlsCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListOrgsCmd_Err {
            get {
                return ResourceManager.GetString("ListOrgsCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.*,b.codename isenable_text,c.username opt_s_user_name 
        ///from s_org a,p_code b,s_user c 
        ///where 
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.opt_s_user_id=c.id
        ///@appendSQL
        ///order by a.p_id,a.sort,a.id asc 的本地化字符串。
        /// </summary>
        internal static string ListOrgsCmd_Sql {
            get {
                return ResourceManager.GetString("ListOrgsCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色组列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListRoleGroupsCmd_Err {
            get {
                return ResourceManager.GetString("ListRoleGroupsCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3029 的本地化字符串。
        /// </summary>
        internal static string ListRoleGroupsCmd_Err_Code {
            get {
                return ResourceManager.GetString("ListRoleGroupsCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.*,b.codename isenable_text,c.username ad_s_user_name from s_rolegroup a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id order by a.id asc 的本地化字符串。
        /// </summary>
        internal static string ListRoleGroupsCmd_Sql {
            get {
                return ResourceManager.GetString("ListRoleGroupsCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListRolesCmd_Err {
            get {
                return ResourceManager.GetString("ListRolesCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3020 的本地化字符串。
        /// </summary>
        internal static string ListRolesCmd_Err_Code {
            get {
                return ResourceManager.GetString("ListRolesCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select a.id,a.rolename,a.roledesc,a.startime,a.endtime,a.addtime
        ///,c.username ad_s_user_name,b.codename isenable_text from s_role a, p_code b,s_user c 
        ///where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id order by a.id asc 的本地化字符串。
        /// </summary>
        internal static string ListRolesCmd_Sql {
            get {
                return ResourceManager.GetString("ListRolesCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询用户菜单树列表 的本地化字符串。
        /// </summary>
        internal static string ListUserMenuTreeCmd {
            get {
                return ResourceManager.GetString("ListUserMenuTreeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户菜单树列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListUserMenuTreeCmd_Err {
            get {
                return ResourceManager.GetString("ListUserMenuTreeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3003 的本地化字符串。
        /// </summary>
        internal static string ListUserMenuTreeCmd_Err_Code {
            get {
                return ResourceManager.GetString("ListUserMenuTreeCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exec p_userMenuTree 1,1,@userid 的本地化字符串。
        /// </summary>
        internal static string ListUserMenuTreeCmd_Sql {
            get {
                return ResourceManager.GetString("ListUserMenuTreeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户列表查询失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ListUsersCmd_Err {
            get {
                return ResourceManager.GetString("ListUsersCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 
        ///a.id,a.username,a.sex,a.alias,a.firstname,a.lastname,
        ///a.firstname+a.lastname as realname,a.qq,a.email,a.idcard,a.mobile,a.fax,a.last_logoutime,
        ///a.addtime,a.opt_s_user_id,a.isenable,a.invalid,b.codename isenable_text 
        ///from 
        ///(
        ///select tt.* from (
        ///select 
        ///row_number() over(order by t.addtime desc) as rowNumber,t.* from s_user t where 1=1 @appendSQL
        ///) tt
        ///
        ///where tt.rowNumber between (@currentpage-1)*@pagesize+1 and @currentpage*@pagesize
        ///
        ///) a
        ///
        ///, p_code b where a.isenable=b.code and b.tab_p_ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ListUsersCmd_Sql {
            get {
                return ResourceManager.GetString("ListUsersCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 
        ///id, username, sex, firstname, lastname, firstname+lastname as realname, qq, email, idcard, mobile, fax, apikey, secretkey, addtime, opt_s_user_id, isenable, invalid 
        ///from 
        ///s_user 
        ///where 
        ///isenable=1 and id=@id and password=@password 的本地化字符串。
        /// </summary>
        internal static string LoginByIdCmd_Sql {
            get {
                return ResourceManager.GetString("LoginByIdCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登陆成功 的本地化字符串。
        /// </summary>
        internal static string LoginCmd {
            get {
                return ResourceManager.GetString("LoginCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码输入错误，请重试！ 的本地化字符串。
        /// </summary>
        internal static string LoginCmd_Err {
            get {
                return ResourceManager.GetString("LoginCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3002 的本地化字符串。
        /// </summary>
        internal static string LoginCmd_Err_Code {
            get {
                return ResourceManager.GetString("LoginCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select 
        ///id, username, sex, firstname, lastname, firstname+lastname as realname, qq, email, idcard, mobile, fax, apikey, secretkey, addtime, ad_s_user_id, isenable, invalid 
        ///from 
        ///s_user 
        ///where 
        ///isenable=1 and username=@username and password=@password 的本地化字符串。
        /// </summary>
        internal static string LoginCmd_Sql {
            get {
                return ResourceManager.GetString("LoginCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户退出成功 的本地化字符串。
        /// </summary>
        internal static string LogoutCmd {
            get {
                return ResourceManager.GetString("LogoutCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户退出失败 的本地化字符串。
        /// </summary>
        internal static string LogoutCmd_Err {
            get {
                return ResourceManager.GetString("LogoutCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3004 的本地化字符串。
        /// </summary>
        internal static string LogoutCmd_Err_Code {
            get {
                return ResourceManager.GetString("LogoutCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_user set logoutime=@logoutime where id=@id 的本地化字符串。
        /// </summary>
        internal static string LogoutCmd_Sql {
            get {
                return ResourceManager.GetString("LogoutCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取照片失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string LookMyPhotoCmd_Err {
            get {
                return ResourceManager.GetString("LookMyPhotoCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3022 的本地化字符串。
        /// </summary>
        internal static string LookMyPhotoCmd_Err_Code {
            get {
                return ResourceManager.GetString("LookMyPhotoCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select photo from s_user where photo is not null and id=@id 的本地化字符串。
        /// </summary>
        internal static string LookMyPhotoCmd_Sql {
            get {
                return ResourceManager.GetString("LookMyPhotoCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作异常，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ResetMyPasswordCmd_Err {
            get {
                return ResourceManager.GetString("ResetMyPasswordCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，新密码重置失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ResetMyPasswordCmd_NewPassword_Err {
            get {
                return ResourceManager.GetString("ResetMyPasswordCmd_NewPassword_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原始密码输入错误，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ResetMyPasswordCmd_OldPassword_Err {
            get {
                return ResourceManager.GetString("ResetMyPasswordCmd_OldPassword_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_user set password=@password where id=@id 的本地化字符串。
        /// </summary>
        internal static string ResetMyPasswordCmd_Sql {
            get {
                return ResourceManager.GetString("ResetMyPasswordCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜您，新密码重置成功！ 的本地化字符串。
        /// </summary>
        internal static string ResetMyPasswordCmd_Tip {
            get {
                return ResourceManager.GetString("ResetMyPasswordCmd_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉，用户新密码重置失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string ResetUserPasswordCmd_Err {
            get {
                return ResourceManager.GetString("ResetUserPasswordCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_user set password=@password where id=@id 的本地化字符串。
        /// </summary>
        internal static string ResetUserPasswordCmd_Sql {
            get {
                return ResourceManager.GetString("ResetUserPasswordCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恭喜您，用户新密码重置成功！ 的本地化字符串。
        /// </summary>
        internal static string ResetUserPasswordCmd_Tip {
            get {
                return ResourceManager.GetString("ResetUserPasswordCmd_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反授权角色[{0}] 的本地化字符串。
        /// </summary>
        internal static string UnEmpowerRoleCmd {
            get {
                return ResourceManager.GetString("UnEmpowerRoleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反授权角色失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UnEmpowerRoleCmd_Err {
            get {
                return ResourceManager.GetString("UnEmpowerRoleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3033 的本地化字符串。
        /// </summary>
        internal static string UnEmpowerRoleCmd_Err_Code {
            get {
                return ResourceManager.GetString("UnEmpowerRoleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from s_role_modopt where tab_s_modopt_id=@tab_s_modopt_id and tab_s_role_id=@tab_s_role_id 的本地化字符串。
        /// </summary>
        internal static string UnEmpowerRoleCmd_Sql {
            get {
                return ResourceManager.GetString("UnEmpowerRoleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新代码[{0}] 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeCmd {
            get {
                return ResourceManager.GetString("UpdateCodeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeCmd_Err {
            get {
                return ResourceManager.GetString("UpdateCodeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3014 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeCmd_Err_Code {
            get {
                return ResourceManager.GetString("UpdateCodeCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update p_code set codename=@codename, codedesc=@codedesc, sort=@sort, editime=@editime, ed_s_user_id=@ed_s_user_id where tab_p_codetype_id=@tab_p_codetype_id and code=@code;
        ///select a.code+&apos;,&apos;+a.tab_p_codetype_id id,a.*,b.codename isenable_text,c.username ad_s_user_name from p_code a, p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.tab_p_codetype_id=@tab_p_codetype_id and a.code=@code; 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateCodeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新代码类型[{0}] 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeTypeCmd {
            get {
                return ResourceManager.GetString("UpdateCodeTypeCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码类型信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeTypeCmd_Err {
            get {
                return ResourceManager.GetString("UpdateCodeTypeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3010 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeTypeCmd_Err_Code {
            get {
                return ResourceManager.GetString("UpdateCodeTypeCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update p_codetype set codetypedesc=@codetypedesc, editime=@editime, ed_s_user_id=@ed_s_user_id where id=@id;
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from p_codetype a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string UpdateCodeTypeCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateCodeTypeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新模块[{0}] 的本地化字符串。
        /// </summary>
        internal static string UpdateModuleCmd {
            get {
                return ResourceManager.GetString("UpdateModuleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateModuleCmd_Err {
            get {
                return ResourceManager.GetString("UpdateModuleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3006 的本地化字符串。
        /// </summary>
        internal static string UpdateModuleCmd_Err_Code {
            get {
                return ResourceManager.GetString("UpdateModuleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_module set modulename=@modulename, href=@href, icon=@icon, sort=@sort, editime=@editime, ed_s_user_id=@ed_s_user_id where id=@id; 
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from s_module a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string UpdateModuleCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateModuleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateMyUrlCmd_Err {
            get {
                return ResourceManager.GetString("UpdateMyUrlCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update p_myurl set url=@url, memo=@memo, tab_p_code_ispublic_id=@tab_p_code_ispublic_id where opt_s_user_id=@opt_s_user_id and id=@id; 
        ///select 
        ///a.*,b.codename isenable_text,c.username opt_s_user_name,d.codename ispublic_text 
        ///from 
        ///p_myurl a,p_code b,s_user c,p_code d
        ///where 
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; 
        ///and a.tab_p_code_ispublic_id=d.code and d.tab_p_codetype_id=&apos;ISPUBLIC&apos; 
        ///and a.opt_s_user_id=c.id 
        ///and a.opt_s_user_id=@opt_s_user_id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string UpdateMyUrlCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateMyUrlCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组织信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateOrgCmd_Err {
            get {
                return ResourceManager.GetString("UpdateOrgCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_org set orgname=@orgname, orgdesc=@orgdesc, tab_s_orgtype_id=@tab_s_orgtype_id, sort=@sort where id=@id; 
        ///select a.*,b.codename isenable_text,c.username opt_s_user_name from s_org a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.opt_s_user_id=c.id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string UpdateOrgCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateOrgCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新角色[{0}] 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleCmd {
            get {
                return ResourceManager.GetString("UpdateRoleCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleCmd_Err {
            get {
                return ResourceManager.GetString("UpdateRoleCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3018 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleCmd_Err_Code {
            get {
                return ResourceManager.GetString("UpdateRoleCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_role set rolename=@rolename,roledesc=@roledesc,startime=DATEADD(s,@startime,&apos;1970-01-01 00:00:00&apos;),endtime=DATEADD(s,@endtime,&apos;1970-01-01 00:00:00&apos;), editime=@editime, ed_s_user_id=@ed_s_user_id where id=@id;
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from s_role a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateRoleCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新角色组[{0}] 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleGroupCmd {
            get {
                return ResourceManager.GetString("UpdateRoleGroupCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色组信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleGroupCmd_Err {
            get {
                return ResourceManager.GetString("UpdateRoleGroupCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3031 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleGroupCmd_Err_Code {
            get {
                return ResourceManager.GetString("UpdateRoleGroupCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_rolegroup set rolegroupdesc=@rolegroupdesc, editime=@editime, ed_s_user_id=@ed_s_user_id where id=@id;
        ///select a.*,b.codename isenable_text,c.username ad_s_user_name from s_rolegroup a,p_code b,s_user c where a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.ad_s_user_id=c.id and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string UpdateRoleGroupCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateRoleGroupCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息更新失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UpdateUserCmd_Err {
            get {
                return ResourceManager.GetString("UpdateUserCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_user set 
        ///sex=@sex,alias=@alias,firstname=@firstname,lastname=@lastname,qq=@qq,email=@email,idcard=@idcard,mobile=@mobile,fax=@fax where id=@id;
        ///select 
        ///a.id,a.username,a.sex,a.alias,a.firstname,a.lastname,
        ///a.firstname+a.lastname as realname,a.qq,a.email,a.idcard,a.mobile,a.fax,a.last_logoutime,
        ///a.addtime,a.opt_s_user_id,a.isenable,a.invalid,b.codename isenable_text 
        ///from 
        ///s_user a, p_code b 
        ///where 
        ///a.isenable=b.code and b.tab_p_codetype_id=&apos;ISENABLE&apos; and a.id=@id; 的本地化字符串。
        /// </summary>
        internal static string UpdateUserCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateUserCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传照片成功 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片上传失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_Err {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3021 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_Err_Code {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片大小超出限制 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_fileLen_Err {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_fileLen_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3025 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_fileLen_Err_Code {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_fileLen_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择照片 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_noChoose_Err {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_noChoose_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3023 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_noChoose_Err_Code {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_noChoose_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 update s_user set photo=@photo, phototype=@phototype where id=@id 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_Sql {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片格式不正确 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_suffix_Err {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_suffix_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3024 的本地化字符串。
        /// </summary>
        internal static string UploadMyPhotoCmd_suffix_Err_Code {
            get {
                return ResourceManager.GetString("UploadMyPhotoCmd_suffix_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密钥验证失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string VerifyUserKeysCmd_Err {
            get {
                return ResourceManager.GetString("VerifyUserKeysCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3027 的本地化字符串。
        /// </summary>
        internal static string VerifyUserKeysCmd_Err_Code {
            get {
                return ResourceManager.GetString("VerifyUserKeysCmd_Err_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select * from s_user where apikey=@apikey 的本地化字符串。
        /// </summary>
        internal static string VerifyUserKeysCmd_Sql {
            get {
                return ResourceManager.GetString("VerifyUserKeysCmd_Sql", resourceCulture);
            }
        }
    }
}
