//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foreworld.Cmd.BookManage {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foreworld.Cmd.BookManage.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string AddBookCmd_Err {
            get {
                return ResourceManager.GetString("AddBookCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string AddBookCmd_Sql {
            get {
                return ResourceManager.GetString("AddBookCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新图书类型添加失败，请重试！ 的本地化字符串。
        /// </summary>
        internal static string AddBookTypeCmd_Err {
            get {
                return ResourceManager.GetString("AddBookTypeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 insert into p_code 
        ///(code,tab_p_codetype_id,p_code,codename,codedesc,sort,addtime,opt_s_user_id,isenable,invalid) 
        ///values 
        ///(@code, @tab_p_codetype_id, @p_code,@codename, @codedesc, @sort, @addtime, @opt_s_user_id, @isenable, @invalid);
        ///select 
        ///a.code+&apos;,&apos;+a.tab_p_codetype_id id,
        ///a.tab_p_codetype_id booktypeid,a.code,a.parentcode,a.codename booktypename,a.codedesc booktypedesc,a.store,
        ///a.addtime,a.opt_s_user_id,a.isenable,a.invalid,
        ///b.codename isenable_text,c.username opt_s_user_name 
        ///from 
        ///p_code a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AddBookTypeCmd_Sql {
            get {
                return ResourceManager.GetString("AddBookTypeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DeleteBookCmd_Err {
            get {
                return ResourceManager.GetString("DeleteBookCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DeleteBookCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteBookCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string DeleteBookTypeCmd_Err {
            get {
                return ResourceManager.GetString("DeleteBookTypeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 delete from p_code where tab_p_codetype_id=@tab_p_codetype_id and code=@code; 的本地化字符串。
        /// </summary>
        internal static string DeleteBookTypeCmd_Sql {
            get {
                return ResourceManager.GetString("DeleteBookTypeCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ListBooksCmd_Err {
            get {
                return ResourceManager.GetString("ListBooksCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ListBooksCmd_Sql {
            get {
                return ResourceManager.GetString("ListBooksCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ListBookTypesCmd_Err {
            get {
                return ResourceManager.GetString("ListBookTypesCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ListBookTypesCmd_Sql {
            get {
                return ResourceManager.GetString("ListBookTypesCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string UpdateBookCmd_Err {
            get {
                return ResourceManager.GetString("UpdateBookCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string UpdateBookCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateBookCmd_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string UpdateBookTypeCmd_Err {
            get {
                return ResourceManager.GetString("UpdateBookTypeCmd_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string UpdateBookTypeCmd_Sql {
            get {
                return ResourceManager.GetString("UpdateBookTypeCmd_Sql", resourceCulture);
            }
        }
    }
}
