//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5472
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foreworld.Rest {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foreworld.Rest.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 表单基础参数验证失败 的本地化字符串。
        /// </summary>
        public static string err_formBaseParamsValidate {
            get {
                return ResourceManager.GetString("err_formBaseParamsValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[{0}]为必填项 的本地化字符串。
        /// </summary>
        public static string err_formParamRequire {
            get {
                return ResourceManager.GetString("err_formParamRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 105 的本地化字符串。
        /// </summary>
        public static string err_formParamRequire_Code {
            get {
                return ResourceManager.GetString("err_formParamRequire_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止访问该命令 的本地化字符串。
        /// </summary>
        public static string err_noAccess {
            get {
                return ResourceManager.GetString("err_noAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 110 的本地化字符串。
        /// </summary>
        public static string err_noAccess_Code {
            get {
                return ResourceManager.GetString("err_noAccess_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到[{0}]命令 的本地化字符串。
        /// </summary>
        public static string err_noCommand {
            get {
                return ResourceManager.GetString("err_noCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 107 的本地化字符串。
        /// </summary>
        public static string err_noCommand_Code {
            get {
                return ResourceManager.GetString("err_noCommand_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部命令禁止访问 的本地化字符串。
        /// </summary>
        public static string err_noPublicCmd {
            get {
                return ResourceManager.GetString("err_noPublicCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 104 的本地化字符串。
        /// </summary>
        public static string err_noPublicCmd_Code {
            get {
                return ResourceManager.GetString("err_noPublicCmd_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会话超时，请重新登陆系统！ 的本地化字符串。
        /// </summary>
        public static string err_noSession {
            get {
                return ResourceManager.GetString("err_noSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 timeout 的本地化字符串。
        /// </summary>
        public static string err_noSession_Code {
            get {
                return ResourceManager.GetString("err_noSession_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请不要重复登陆！ 的本地化字符串。
        /// </summary>
        public static string err_notReLogin {
            get {
                return ResourceManager.GetString("err_notReLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 102 的本地化字符串。
        /// </summary>
        public static string err_notReLogin_Code {
            get {
                return ResourceManager.GetString("err_notReLogin_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[apikey]不能为空 的本地化字符串。
        /// </summary>
        public static string err_paramApiKeyIsNotEmpty {
            get {
                return ResourceManager.GetString("err_paramApiKeyIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 108 的本地化字符串。
        /// </summary>
        public static string err_paramApiKeyIsNotEmpty_Code {
            get {
                return ResourceManager.GetString("err_paramApiKeyIsNotEmpty_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[{0}]不能为空 的本地化字符串。
        /// </summary>
        public static string err_paramIsNotEmpty {
            get {
                return ResourceManager.GetString("err_paramIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 101 的本地化字符串。
        /// </summary>
        public static string err_paramIsNotEmpty_Code {
            get {
                return ResourceManager.GetString("err_paramIsNotEmpty_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[response]格式为json/xml 的本地化字符串。
        /// </summary>
        public static string err_paramResponse {
            get {
                return ResourceManager.GetString("err_paramResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[signature]不能为空 的本地化字符串。
        /// </summary>
        public static string err_paramSignatureIsNotEmpty {
            get {
                return ResourceManager.GetString("err_paramSignatureIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 109 的本地化字符串。
        /// </summary>
        public static string err_paramSignatureIsNotEmpty_Code {
            get {
                return ResourceManager.GetString("err_paramSignatureIsNotEmpty_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数[{0}]值验证失败 的本地化字符串。
        /// </summary>
        public static string err_paramValueRegex {
            get {
                return ResourceManager.GetString("err_paramValueRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 106 的本地化字符串。
        /// </summary>
        public static string err_paramValueRegex_Code {
            get {
                return ResourceManager.GetString("err_paramValueRegex_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signature验证失败 的本地化字符串。
        /// </summary>
        public static string err_signatureValidate {
            get {
                return ResourceManager.GetString("err_signatureValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 110 的本地化字符串。
        /// </summary>
        public static string err_signatureValidate_Code {
            get {
                return ResourceManager.GetString("err_signatureValidate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 select id,user_name from sysmanage_user where user_name=@username and password=@password 的本地化字符串。
        /// </summary>
        public static string sql_login {
            get {
                return ResourceManager.GetString("sql_login", resourceCulture);
            }
        }
    }
}
